### ISSUE TITLE
[TicTacToe] Отображение

### ISSUE THREAD

**Issue by pavel-b-novikov** [dymova/nsudotnet#4]
Единственное, что мне не понравилось в задаче - это зависимость контроллера на консольную отображалку. Подумайте как можно развернуть эту зависимость так, чтобы освободить контроллер от зависимости на графику (чего в идеале быть и не должно).

**Comment by dymova** [comment]
переделала

**Comment by pavel-b-novikov** [comment]
Да, именно этого я и хотел. Вы свободны.
